version: "3"
services:
 nginx:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
 node-app:
  build: .
  environment:
   - PORT=3000
  depends_on:
   - mongo

 mongo:
  image: mongo
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=mvakqo,119
  volumes:
   - mongo-db:/data/db
  ports:
   - "27018:27017"

 redis:
  image: redis
volumes:
 mongo-db: 
   
