version: "3"
services:
 nginx:
  image: nginx
  ports:
   - "8080:80"
 node-app:
  build:
   context: .
   args:
    NODE_ENV: production
  environment:
   - NODE_ENV=production
  command: node index.js
