version: "3"
services:
 nginx:
  image: nginx
  ports:
  - "8080:80"
 node-app:
  build:
   context: .
   args:
    NODE_ENV: development
  volumes:
   - ./:/app
   - /app/node_modules
  environment:
   - NODE_ENV=development
  command: npm run dev
